language: c

env:
    - SMVERSION=1.8

matrix:
    fast_finish: true
    
before_install:
    - apt-get update
    - apt-get install gcc-multilib
    - apt-get install lynx
    - apt-get install lib32stdc++6

before_script:
    - SMLATEST=`curl "https://www.sourcemod.net/smdrop/$SMVERSION/sourcemod-latest-linux"`
    - SMPACKAGE="https://www.sourcemod.net/smdrop/$SMVERSION/$SMLATEST"
    - wget $SMPACKAGE
    - tar -xzf $(basename "$SMPACKAGE")
    - cp Ticketron.sp addons/sourcemod/scripting/
    - cp include/SteamWorks.inc addons/sourcemod/scripting/include
    - cp include/steamtools.inc addons/sourcemod/scripting/include
    - cp include/morecolors_store.inc addons/sourcemod/scripting/include
    - cp include/Ticketron.inc addons/sourcemod/scripting/include
    - cp include/EventLogs.inc addons/sourcemod/scripting/include
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - chmod +x compile.sh
    
script: 
    - ./compile.sh Ticketron.sp   
  
deploy:
  provider: releases
  api_key: "$githubkey"
  file: "$TRAVIS_BUILD_DIR/addons/sourcemod/scripting/compiled/Ticketron.smx"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false